use master
go

CREATE DATABASE BanLinhKienDienTu
go

USE BanLinhKienDienTu
go

CREATE TABLE [NhaCungCap] (
	[MaNCC] NVARCHAR(11) NOT NULL UNIQUE,
	[TenNCC] NVARCHAR(255),
	[Sdt] NVARCHAR(11),
	[DiaChi] NVARCHAR(255),
	[Email] NVARCHAR(255),
	PRIMARY KEY([MaNCC])
);
GO

CREATE TABLE [PhieuNhap] (
	[MaPN] NVARCHAR(11) NOT NULL UNIQUE,
	[NgayNhap] DATE,
	[GiaNhap] FLOAT,
	[SoLuong] INT,
	[ThanhTien] FLOAT,
	[MaNCC] NVARCHAR(11),
	[MaSP] NVARCHAR(11),
	PRIMARY KEY([MaPN])
);
GO

CREATE TABLE [SanPham] (
	[MaSP] NVARCHAR(11) NOT NULL UNIQUE,
	[TenSP] NVARCHAR(255),
	[NgaySanXuat] DATE,
	[GiaNhap] FLOAT,
	[GiaBan] FLOAT,
	[TrangThai] INT,
	[MaLoai] NVARCHAR(11),
	PRIMARY KEY([MaSP])
);
GO

CREATE TABLE [LoaiSanPham] (
	[MaLoai] NVARCHAR(11) NOT NULL UNIQUE,
	[TenLoai] NVARCHAR(255),
	PRIMARY KEY([MaLoai])
);
GO

CREATE TABLE [GioHang] (
	[MaGH] NVARCHAR(11) NOT NULL UNIQUE,
	[SoLuong] INT,
	[ThanhTien] FLOAT,
	[MaKH] NVARCHAR(11),
	PRIMARY KEY([MaGH])
);
GO

CREATE TABLE [HoaDon_SanPham] (
	[MaHD] NVARCHAR(11) NOT NULL,
	[MaSP] NVARCHAR(11) NOT NULL,
	PRIMARY KEY([MaHD], [MaSP])
);
GO

CREATE TABLE [HoaDon] (
	[MaHD] NVARCHAR(11) NOT NULL UNIQUE,
	[DonViTinh] NVARCHAR(255),
	[DonGia] FLOAT,
	[SoLuong] INT,
	[ThanhTien] FLOAT,
	[NgayXuatHD] DATE,
	[MaKH] NVARCHAR(11),
	[MaNV] NVARCHAR(11),
	PRIMARY KEY([MaHD])
);
GO

CREATE TABLE [KhachHang] (
	[MaKH] NVARCHAR(11) NOT NULL UNIQUE,
	[TenKH] NVARCHAR(255),
	[DiaChi] NVARCHAR(255),
	[Sdt] NVARCHAR(11),
	[GioiTinh] NVARCHAR(5),
	PRIMARY KEY([MaKH])
);
GO

CREATE TABLE [ChucVu] (
	[MaCV] NVARCHAR(11) NOT NULL UNIQUE,
	[TenCV] NVARCHAR(255),
	PRIMARY KEY([MaCV])
);
GO

CREATE TABLE [NhanVien] (
	[MaNV] NVARCHAR(11) NOT NULL UNIQUE,
	[Sdt] NVARCHAR(11),
	[DiaChi] NVARCHAR(255),
	[NgaySinh] DATE,
	[GioiTinh] NVARCHAR(5),
	[MaCV] NVARCHAR(11),
	PRIMARY KEY([MaNV])
);
GO

CREATE TABLE [ThongKePhieuNhap] (
	[MaTKPN] NVARCHAR(11) NOT NULL UNIQUE,
	[SoLuongDaNhap] INT,
	[TongSoTienNhap] FLOAT,
	[TongDonGiaNhap] FLOAT,
	[MaNV] NVARCHAR(11),
	PRIMARY KEY([MaTKPN])
);
GO

CREATE TABLE [ThongKeHoaDon] (
	[MaTKHD] NVARCHAR(11) NOT NULL UNIQUE,
	[NgayBan] DATE,
	[SoLuongDaBan] INT,
	[TongDonGiaBan] FLOAT,
	[TongGiaBan] FLOAT,
	[MaNV] NVARCHAR(11),
	PRIMARY KEY([MaTKHD])
);
GO

CREATE TABLE [NguoiDung] (
	[MaND] NVARCHAR(11) NOT NULL UNIQUE,
	[Email] NVARCHAR(255),
	[MatKhau] NVARCHAR(255),
	PRIMARY KEY([MaND])
);
GO

CREATE TABLE [NguoiDung_PhanQuyen] (
	[MaND] NVARCHAR(11) NOT NULL,
	[MaPQ] NVARCHAR(11) NOT NULL,
	PRIMARY KEY([MaND], [MaPQ])
);
GO

CREATE TABLE [PhanQuyen] (
	[MaPQ] NVARCHAR(11) NOT NULL UNIQUE,
	[TenNhomQuyen] NVARCHAR(255),
	PRIMARY KEY([MaPQ])
);
GO

CREATE TABLE [ChiTietPhanQuyen] (
	[MaCTPQ] NVARCHAR(11) NOT NULL UNIQUE,
	[QuyenDuocCapPhep] NVARCHAR(255),
	[KiemTraHanhDong] INT,
	[MaPQ] NVARCHAR(11),
	PRIMARY KEY([MaCTPQ])
);
GO

CREATE TABLE [SanPham_Gio] (
	[MaSP] NVARCHAR(11) NOT NULL,
	[MaGH] NVARCHAR(11) NOT NULL,
	PRIMARY KEY([MaSP], [MaGH])
);
GO

ALTER TABLE [HoaDon_SanPham]
ADD FOREIGN KEY([MaHD]) REFERENCES [HoaDon]([MaHD])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [NguoiDung_PhanQuyen]
ADD FOREIGN KEY([MaND]) REFERENCES [NguoiDung]([MaND])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [NguoiDung_PhanQuyen]
ADD FOREIGN KEY([MaPQ]) REFERENCES [PhanQuyen]([MaPQ])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [PhieuNhap]
ADD FOREIGN KEY([MaNCC]) REFERENCES [NhaCungCap]([MaNCC])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [PhieuNhap]
ADD FOREIGN KEY([MaSP]) REFERENCES [SanPham]([MaSP])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [SanPham]
ADD FOREIGN KEY([MaLoai]) REFERENCES [LoaiSanPham]([MaLoai])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [SanPham_Gio]
ADD FOREIGN KEY([MaSP]) REFERENCES [SanPham]([MaSP])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [SanPham_Gio]
ADD FOREIGN KEY([MaGH]) REFERENCES [GioHang]([MaGH])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [GioHang]
ADD FOREIGN KEY([MaKH]) REFERENCES [KhachHang]([MaKH])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [HoaDon_SanPham]
ADD FOREIGN KEY([MaSP]) REFERENCES [SanPham]([MaSP])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [HoaDon]
ADD FOREIGN KEY([MaKH]) REFERENCES [KhachHang]([MaKH])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [NhanVien]
ADD FOREIGN KEY([MaCV]) REFERENCES [ChucVu]([MaCV])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [HoaDon]
ADD FOREIGN KEY([MaNV]) REFERENCES [NhanVien]([MaNV])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [ThongKeHoaDon]
ADD FOREIGN KEY([MaNV]) REFERENCES [NhanVien]([MaNV])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [ThongKePhieuNhap]
ADD FOREIGN KEY([MaNV]) REFERENCES [NhanVien]([MaNV])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [ChiTietPhanQuyen]
ADD FOREIGN KEY([MaPQ]) REFERENCES [PhanQuyen]([MaPQ])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
