/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.XacThuc;

import static Controller.KiemSoatLoiInput.kiemtraEmail;
import static Controller.KiemSoatLoiInput.kiemtraTrongInput;
import java.awt.HeadlessException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Kaiser
 */
public class QuenMatKhau extends javax.swing.JFrame {

    /**
     * Creates new form QuenMatKhau
     */
    public QuenMatKhau() {
        initComponents();
        setTitle("Quên Mật Khẩu");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnQuenMatKhau = new javax.swing.JPanel();
        lbEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lbDangKy = new javax.swing.JLabel();
        btnLayCode = new javax.swing.JButton();
        lbMaXacThuc = new javax.swing.JLabel();
        txtMaXacThuc = new javax.swing.JTextField();
        btnQuenMK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnQuenMatKhau.setBackground(new java.awt.Color(175, 217, 243));

        lbEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(255, 255, 255));
        lbEmail.setText("Email:");

        txtEmail.setBackground(new java.awt.Color(175, 217, 243));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtEmail.setOpaque(true);

        lbDangKy.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbDangKy.setForeground(new java.awt.Color(255, 255, 255));
        lbDangKy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SignIn_Header.png"))); // NOI18N
        lbDangKy.setText("   Quên mật khẩu");

        btnLayCode.setBackground(new java.awt.Color(22, 72, 99));
        btnLayCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLayCode.setForeground(new java.awt.Color(255, 255, 255));
        btnLayCode.setText("Get Code");

        lbMaXacThuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMaXacThuc.setForeground(new java.awt.Color(255, 255, 255));
        lbMaXacThuc.setText("Mã xác thực:");

        txtMaXacThuc.setBackground(new java.awt.Color(175, 217, 243));
        txtMaXacThuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaXacThuc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtMaXacThuc.setOpaque(true);

        btnQuenMK.setBackground(new java.awt.Color(22, 72, 99));
        btnQuenMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuenMK.setForeground(new java.awt.Color(255, 255, 255));
        btnQuenMK.setText("Hoàn tất");
        btnQuenMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuenMKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnQuenMatKhauLayout = new javax.swing.GroupLayout(pnQuenMatKhau);
        pnQuenMatKhau.setLayout(pnQuenMatKhauLayout);
        pnQuenMatKhauLayout.setHorizontalGroup(
            pnQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQuenMatKhauLayout.createSequentialGroup()
                .addGroup(pnQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnQuenMatKhauLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(lbDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnQuenMatKhauLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(pnQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnQuenMatKhauLayout.createSequentialGroup()
                                .addComponent(lbMaXacThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(txtMaXacThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLayCode, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnQuenMatKhauLayout.createSequentialGroup()
                                .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(pnQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnQuenMatKhauLayout.createSequentialGroup()
                    .addContainerGap(208, Short.MAX_VALUE)
                    .addComponent(btnQuenMK, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(175, 175, 175)))
        );
        pnQuenMatKhauLayout.setVerticalGroup(
            pnQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQuenMatKhauLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbDangKy)
                .addGap(56, 56, 56)
                .addGroup(pnQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMaXacThuc)
                    .addComponent(txtMaXacThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLayCode, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(pnQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnQuenMatKhauLayout.createSequentialGroup()
                    .addContainerGap(254, Short.MAX_VALUE)
                    .addComponent(btnQuenMK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnQuenMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnQuenMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuenMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuenMKActionPerformed
        kiemtraHopLe(txtEmail, txtMaXacThuc, this);
    }//GEN-LAST:event_btnQuenMKActionPerformed

    public static void kiemtraHopLe(JTextField txtEmail, JTextField txtMaXacThuc, JFrame pnQuenMatKhau) {
        try {
            String email = txtEmail.getText();
            String ma = txtMaXacThuc.getText();
            String thongBaoLoi = "";

            if (kiemtraTrongInput(ma)) {
                thongBaoLoi += "Mã xác thực không được để trống\n";
            }
            if (kiemtraTrongInput(email)) {
                thongBaoLoi += "Email không được để trống\n";
            } else if (!kiemtraEmail(email)) {
                JOptionPane.showMessageDialog(null, "Email không hợp lệ");
                return;
            }
            if (!thongBaoLoi.isEmpty()) {
                JOptionPane.showMessageDialog(null, thongBaoLoi.trim());
            } else {
                JOptionPane.showMessageDialog(null, "Mật khẩu đã được gửi tới email" + email);
                pnQuenMatKhau.dispose();
            }

        } catch (HeadlessException e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuenMatKhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLayCode;
    private javax.swing.JButton btnQuenMK;
    private javax.swing.JLabel lbDangKy;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbMaXacThuc;
    private javax.swing.JPanel pnQuenMatKhau;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaXacThuc;
    // End of variables declaration//GEN-END:variables
}
